  1) Stages/Devel-2020

Currently Loaded Modules:
  1) Stages/Devel-2019a          (S)    14) SQLite/.3.27.2     (H)  27) libffi/.3.2.1                  (H)  40) FFmpeg/.4.1.3                      (H)
  2) GCC/8.3.0                          15) expat/.2.2.6       (H)  28) libyaml/.0.2.2                 (H)  41) numactl/2.0.12
  3) GCCcore/.8.3.0              (H)    16) libpng/.1.6.36     (H)  29) Java/1.8                            42) MPFR/4.0.2
  4) binutils/.2.32              (H)    17) freetype/.2.10.0   (H)  30) PostgreSQL/11.2                     43) NCCL/2.4.6-1-CUDA-10.1.105         (g)
  5) nvidia/.418.87.00           (H,g)  18) gperf/.3.1         (H)  31) protobuf/.3.7.1                (H)  44) libunwind/.1.3.1                   (H)
  6) UCX/1.6.1                          19) util-linux/.2.33.1 (H)  32) gflags/.2.2.2                  (H)  45) glog/.0.4.0                        (H)
  7) pscom/.5.4.2-1-CUDA         (H)    20) fontconfig/.2.13.1 (H)  33) libspatialindex/.1.9.0         (H)  46) PyTorch/1.1.0-GPU-Python-3.6.8     (g)
  8) ParaStationMPI/5.4.0-1-CUDA        21) X11/20190311            34) NASM/.2.14.02                  (H)  47) Szip/.2.1.1                        (H)
  9) bzip2/.1.0.6                (H)    22) Tk/.8.6.9          (H)  35) libjpeg-turbo/.2.0.2           (H)  48) HDF5/1.10.5-serial
 10) zlib/.1.2.11                (H)    23) GMP/6.1.2               36) Python/3.6.8                        49) h5py/2.9.0-serial-Python-3.6.8
 11) ncurses/.6.1                (H)    24) XZ/.5.2.4          (H)  37) imkl/.2019.3.199               (H)  50) Keras/2.2.4-GPU-Python-3.6.8
 12) libreadline/.8.0            (H)    25) libxml2/.2.9.9     (H)  38) SciPy-Stack/2019a-Python-3.6.8      51) Horovod/0.16.2-GPU-Python-3.6.8    (g)
 13) Tcl/8.6.9                          26) libxslt/.1.1.33    (H)  39) x264/.20190429                 (H)  52) TensorFlow/1.13.1-GPU-Python-3.6.8 (g)

  Where:
   H:  Hidden Module
   S:  Module is Sticky, requires --force to unload or purge
   g:  built for GPU

 

/var/spool/parastation/jobs/194040: line 22: conda: command not found
cpu_bind=NONE - dp-dam01, task  0  0 [6061]: mask 0xffffffffffffffffffffffff set
cpu_bind=NONE - dp-dam01, task  1  1 [6062]: mask 0xffffffffffffffffffffffff set
cpu_bind=NONE - dp-dam01, task  3  3 [6063]: mask 0xffffffffffffffffffffffff set
cpu_bind=NONE - dp-dam01, task  2  2 [6064]: mask 0xffffffffffffffffffffffff set
<PSP:r0000001:extoll:EXTOLL disabled : rma2_open() : Communication with the OS driver failed>
<PSP:r0000003:extoll:EXTOLL disabled : rma2_open() : Communication with the OS driver failed>
<PSP:r0000002:extoll:EXTOLL disabled : rma2_open() : Communication with the OS driver failed>
<PSP:r0000000:extoll:EXTOLL disabled : rma2_open() : Communication with the OS driver failed>
Traceback (most recent call last):
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
Traceback (most recent call last):
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
Traceback (most recent call last):
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
Traceback (most recent call last):
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 243, in load_module
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 243, in load_module
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 243, in load_module
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 343, in load_dynamic
    return load_dynamic(name, filename, file)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 343, in load_dynamic
    return load_dynamic(name, filename, file)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 343, in load_dynamic
    return load_dynamic(name, filename, file)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    return _load(spec)
ImportError: libcublas.so.10: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    return _load(spec)
ImportError: libcublas.so.10: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    return _load(spec)
ImportError: libcublas.so.10: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    import tensorflow as tf
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    import tensorflow as tf
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    import tensorflow as tf
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    import tensorflow as tf
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/software/skylake/Stages/Devel-2019a/software/TensorFlow/1.13.1-GCCcore-8.3.0-GPU-Python-3.6.8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/p/project/joaiml/ingolfsson1/anaconda3/envs/covid_env/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
srun: error: dp-dam01: tasks 0-3: Exited with exit code 1
